const TableData = [
  {
    id: 1,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolor ',
    date: '22-22-2222',
  },
  {
    id: 2,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolor ',
    date: '22-22-2222',
  },
  {
    id: 3,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolor ',
    date: '22-22-2222',
  },
  {
    id: 4,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolor ',
    date: '22-22-2222',
  },
  {
    id: 5,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolor ',
    date: '22-22-2222',
  },
  {
    id: 6,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolo',
    date: '22-22-2222',
  },
  {
    id: 7,
    image: require('../../../../assets/Images/table-watch.png'),
    name: 'HUAWEI Watch 3 Pro',
    per: 12,
    price: 99,
    sold: 20,
    available: 20,
    revenue: 1980,
    info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod non Lorem ipsum dolo',
    date: '22-22-2222',
  },
];

export default TableData;
